#!/bin/sh

TITLE=""
COMMENT=""
CHAR="█"
PROMPT=""
PROGRESS=0
LENGTH=50

usage () {
    cat << EOF
Usage: COMMAND | ${0##*/} [-b BAR] [-p PROMPT] [-t TITLE] [-l LENGTH]...
EOF
}

if [ ! -p "/dev/stdin" ]; then
    usage
    exit 1
fi

while [ $# -gt 0 ]
do
    ARG="$1"
    shift
    case "$ARG" in
        -b)
            CHAR="$1"
            shift
            ;;
        -p)
            PROMPT="$1"
            shift
            ;;
        -t)
            TITLE="$1: "
            shift
            ;;
        -l)
            if printf "$1" | grep -qE '^[0-9]+$' > /dev/null 2>&1; then
                if [ "$1" -ge 10 ] && [ "$1" -le 100 ]; then
                    LENGTH="$1"
                fi
            fi
            shift
            ;;
        *)
            ;;
    esac
done

printf "\n\n"

while read -r LINE
do
    if printf "%s" "$LINE" | grep -qE '^[0-9]+$' > /dev/null 2>&1; then
        PROGRESS="$LINE"
    elif printf "%s" "$LINE" | grep '^#' > /dev/null 2>&1; then
        COMMENT=$(printf "%s\n" "$LINE" | sed 's/^#//')
    fi

    BAR=$(yes "$CHAR" | head -n "$(( PROGRESS / ( 100 / LENGTH )  ))" 2> /dev/null | tr -d '\n')
    if [ -n "$PROMPT" ] && [ "$PROGRESS" -lt 100 ]; then
        BAR=$(printf "%s" "$BAR" | sed s/"$CHAR"$/"$PROMPT"/)
    fi

    printf "\r\033[2A"
    printf "%s%s\033[K\n" "$TITLE" "$COMMENT"
    printf "%3d%% %s\n" "$PROGRESS" "$BAR"
done
